services:
  - type: worker
    name: sheet-rat-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_TOKEN
        value: 8381146744:AAGifGXeiWvMFTZ3jRzWrse6hz3-uslkSkI
      - key: CRYPTO_TOKEN
        value: 560696:AAGcjeTB1aNDJAajb5g3YGqzQkZ7ZjH1DJS
      - key: ADMIN_ID
        value: 5035967198
